name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - chore/github-actions
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kwdowik/car-rental-api
          tag_with_ref: true
